config/routes.rb
Rails.application.routes.draw do
  get 'publishers/new'

  get 'publishers/create'

  get 'publishers/update'

  get 'publishers/edit'

  get 'publishers/destroy'

  get 'publishers/index'

  get 'publishers/show'

  get 'authors/new'

  get 'authors/create'

  get 'authors/update'

  get 'authors/edit'

  get 'authors/destroy'

  get 'authors/index'

  get 'authors/show'

  get 'categories/new'

  get 'categories/create'

  get 'categories/update'

  get 'categories/edit'

  get 'categories/destroy'

  get 'categories/index'

  get 'categories/show'

  get 'books/new'

  get 'books/create'

  get 'books/update'

  get 'books/edit'

  get 'books/destroy'

  get 'books/index'

  get 'books/show'

  get 'about/index'

  get 'about' => 'about#index'

  root 'books#index'

  resources :books
  resources :authors
  resources :categories
  resources :publishers

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :category
  belongs_to :author
  belongs_to :publisher
  validates :title, presence: true
  validates :isbn, presence: true
  validates :author_id, presence: true
  validates :category_id, presence: true
  validates :publisher_id, presence: true
  validates :price, presence: true

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books

  validates :name, presence: true,
            length: {minimum:3}
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  has_many :books
  validates :name, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @page_title = 'About Us';
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def new
    @page_title = 'Add new Author'
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      flash[:notice] = "Author Created"
      redirect_to authors_path
    else
      render 'new'
    end
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end

  private
    def author_params
      params.require(:author).permit(:first_name, :last_name)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @page_title = 'Add Book'
    @book = Book.new
    @category = Category.new
    @author = Author.new
    @publisher = Publisher.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book Created"
      redirect_to books_path
    else
      render 'new'
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    flash[:notice] = "Book Updated"
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book Removed"
    redirect_to books_path
  end

  def index
    @books = Book.all
    @categories = Category.all
  end

  def show
    @book = Book.find(params[:id])
    @categories = Category.all
  end

  private
    def book_params
      params.require(:book).permit(:title, :category_id, :author_id, :publisher_id, :isbn, :price, :buy, :format, :excerpt, :pages, :year)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @page_title = 'Add new Category'
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category Created"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @books = @category.books
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def new
    @page_title = 'Add new Publisher'
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new(publisher_params)
    if @publisher.save
      flash[:notice] = "Publisher Created"
      redirect_to publishers_path
    else
      render 'new'
    end
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end

  private
    def publisher_params
      params.require(:publisher).permit(:name)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/about/index.html.erb
<h1><%= @page_title %></h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

app/views/authors/destroy.html.erb
<h1>Authors#destroy</h1>
<p>Find me in app/views/authors/destroy.html.erb</p>

app/views/authors/edit.html.erb
<h1>Authors#edit</h1>
<p>Find me in app/views/authors/edit.html.erb</p>

app/views/authors/index.html.erb
<h1>Authors#index</h1>
<p>Find me in app/views/authors/index.html.erb</p>

app/views/authors/new.html.erb
<h2>Add New Author</h2>

<%= form_for @author do |f| %>
  <!-- check for errors -->
  <% if @author.errors.any? %>
    <% @author.errors.full_messages.each do |msg| %>
      <!-- show errors -->
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <%end%>
  <%end%>
  <div class="form-group">
    <%= f.label :firstname %><br/>
    <%= f.text_field :first_name, class:'from-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :lastname %><br/>
    <%= f.text_field :last_name,type:'text', class:'from-control' %><br/>
  </div>

  <%= f.submit "Submit", class:'btn btn-primary' %>
  <%= link_to "Cancel", authors_path, class:'btn btn-default' %>
<%end%>

app/views/authors/show.html.erb
<h1>Authors#show</h1>
<p>Find me in app/views/authors/show.html.erb</p>

app/views/authors/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h2>Edit Book</h2>

<%= form_for @book do |f| %>
  <!-- check for errors -->
  <% if @book.errors.any? %>
    <% @book.errors.full_messages.each do |msg| %>
      <!-- show errors -->
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <%end%>
  <%end%>
  <div class="form-group">
    <%= f.label :title %><br/>
    <%= f.text_field :title, class:'from-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :isbn %><br/>
    <%= f.text_field :isbn, class:'from-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :author %><br/>
    <%= f.select :author_id, Category.all.collect {|x| [x.name,x.id]},{:includ_blank => 'Select One'}, class:'from-control' %><br/><br/>
  </div>

  <div class="form-group">
    <%= f.label :category %><br/>
    <%= f.select :category_id, Author.all.collect {|x| [x.first_name+' '+x.last_name,x.id]},{:includ_blank => 'Select One'}, class:'from-control' %><br/><br/>
  </div>

  <div class="form-group">
    <%= f.label :publisher %><br/>
    <%= f.select :publisher_id, Publisher.all.collect {|x| [x.name,x.id]},{:includ_blank => 'Select One'}, class:'from-control' %><br/><br/>
  </div>

  <div class="form-group">
    <%= f.label :format %><br/>
    <%= f.text_field :format, class:'from-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :coverpath %><br/>
    <%= f.text_field :coverpath, class:'from-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :excerpt %><br/>
    <%= f.text_area :excerpt, class:'from-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :pages %><br/>
    <%= f.number_field :pages, class:'from-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :price %><br/>
    <%= f.text_field :price, class:'from-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :buy %><br/>
    <%= f.text_field :pages, class:'from-control' %><br/>
  </div>

  <%= f.submit "Submit", class:'btn btn-primary' %>
  <%= link_to "Cancel", books_path, class:'btn btn-default' %>
<% end %>

app/views/books/index.html.erb
<div id="books-index">
  <% @books.each_slice(4) do |book| %>
    <div class="row">
      <% book.each do |book| %>
        <div class="col-md-3 col-sm-3">
          <h4><%= book.title %></h4>
          <%= image_tag(book.coverpath,:size => "200x250") %><br><br>
          <%= link_to 'Read More', book_path(book),class:'btn btn-primary',style:"width: 100%;"%><br><br>
        </div>
      <%end%>
    </div>
  <% end %>
</div>

app/views/books/new.html.erb
<h2>Add New Book</h2>

<%= form_for @book do |f| %>
  <!-- check for errors -->
  <% if @book.errors.any? %>
    <% @book.errors.full_messages.each do |msg| %>
      <!-- show errors -->
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <%end%>
  <%end%>
  <div class="form-group">
    <%= f.label :title %><br/>
    <%= f.text_field :title, class:'from-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :isbn %><br/>
    <%= f.text_field :isbn, class:'from-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :author %><br/>
    <%= f.select :author_id, Category.all.collect {|x| [x.name,x.id]},{:includ_blank => 'Select One'}, class:'from-control' %><br/><br/>
  </div>

  <div class="form-group">
    <%= f.label :category %><br/>
    <%= f.select :category_id, Author.all.collect {|x| [x.first_name+' '+x.last_name,x.id]},{:includ_blank => 'Select One'}, class:'from-control' %><br/><br/>
  </div>

  <div class="form-group">
    <%= f.label :publisher %><br/>
    <%= f.select :publisher_id, Publisher.all.collect {|x| [x.name,x.id]},{:includ_blank => 'Select One'}, class:'from-control' %><br/><br/>
  </div>

  <div class="form-group">
    <%= f.label :format %><br/>
    <%= f.text_field :format, class:'from-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :coverpath %><br/>
    <%= f.text_field :coverpath, class:'from-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :excerpt %><br/>
    <%= f.text_area :excerpt, class:'from-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :pages %><br/>
    <%= f.number_field :pages, class:'from-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :price %><br/>
    <%= f.text_field :price, class:'from-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :buy %><br/>
    <%= f.text_field :pages, class:'from-control' %><br/>
  </div>

  <%= f.submit "Submit", class:'btn btn-primary' %>
  <%= link_to "Cancel", books_path, class:'btn btn-default' %>
<% end %>

app/views/books/show.html.erb
<div id="books-show">
  <h2><%= @book.title %></h2>
  <div class="books-show-left">
    <%= image_tag(@book.coverpath, :size => "200x250")%>
  </div>
  <div class="books-show-right">
    <h3>Book Info:</h3>
    <ul>
      <li><strong>Categories: </strong> <%= @book.category.name %></li>
      <li><strong>Author: </strong> <%= @book.author.first_name %> <%= @book.author.last_name %></li>
      <li><strong>Pusblisher: </strong> <%= @book.publisher.name %></li>
      <li><strong>Year: </strong> <%= @book.year %></li>
      <li><strong>ISBN: </strong> <%= @book.isbn %></li>
      <li><strong>Format: </strong> <%= @book.format %></li>
      <li><strong>Pages: </strong> <%= @book.pages %></li>
    </ul><br><br>
  </div>
  <div class="clearfix">
    <h4>Excerpt</h4>
    <p><%= @book.excerpt %></p>
  </div>
  <h3>Admin Functions</h3>
  <%= link_to 'Edit', edit_book_path(@book.id)%> | <%= link_to 'Delete', book_path(@book), method: :delete, data: {confirm: 'Are you sure ?'} %>
</div>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/new.html.erb
<h2>Add Category</h2>

<%= form_for @category do |f| %>
  <!-- check for errors -->
  <% if @category.errors.any? %>
    <% @category.errors.full_messages.each do |msg| %>
      <!-- show errors -->
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <%end%>
  <%end%>
  <div class="form-group">
    <%= f.label :name %><br/>
    <%= f.text_field :name, class:'from-control' %><br/>
  </div>

  <%= f.submit "Submit", class:'btn btn-primary' %>
  <%= link_to "Cancel", categories_path, class:'btn btn-default' %>
<%end%>

app/views/categories/show.html.erb
<h2><%= @category.name %></h2>
<div id="books-index">
  <% @books.each_slice(4) do |book| %>
    <div class="row">
      <% book.each do |book| %>
        <div class="col-md-3 col-sm-3">
          <h4><%= book.title %></h4>
          <%= image_tag(book.coverpath,:size => "200x250") %><br><br>
          <%= link_to 'Read More', book_path(book),class:'btn btn-primary',style:"width: 100%;"%><br><br>
        </div>
      <%end%>
    </div>
  <% end %>
</div>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title  ? @page_title : 'Welcome' %> | The BookStore</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="<%= params[:controller] == 'books' ? 'active' : '' %>"><%= link_to 'Home', root_path%></li>
          <li class="<%= params[:controller] == 'about  ' ? 'active' : '' %>"><%= link_to 'About', about_path%></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Add New <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Book", new_book_path %></li>
              <li><%= link_to "Category", new_category_path %></li>
              <li><%= link_to "Author", new_author_path %></li>
              <li><%= link_to "Publisher", new_publisher_path %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <header>
    <div class="container">
      <h1>The BookStore <small><%= @page_title  ? @page_title : 'Welcome' %></small></h1>
    </div>
  </header>
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <!-- alerts & messages -->
        <% if flash[:notice] %>
          <div class="alert alert-success"><%= flash[:notice]%></div>
        <% end %>
        <% if flash[:alert] %>
          <div class="alert alert-danger"><%= flash[:alert]%></div>
        <% end %>
        <%= yield %>
      </div>
      <div class="col-md-4">
        <%= render 'partials/sidebar' %>
      </div>
    </div>
  </div>
</section>

<footer>
  <div class="container">
    <p>Copyright &copy; 2018 All Right Reserved</p>
  </div>
</footer>

</body>
</html>

app/views/partials/_sidebar.html.erb
<% if params[:controller] == 'about'%>
<div class="well">
  <h3>Location Info</h3>
  <ul>
    <li>The BookStore</li>
    <li>No 242,SatYoun St, DawBon Tsp</li>
    <li>Yangon</li>
    <li>Phone:12456789</li>
    <li>Email:rails4.2@test.com</li>
  </ul>
</div>
<%end %>
<% if params[:controller] == 'books' && params[:action] ==  'index' || params[:action] == 'show' %>
<h4>Categories</h4>
<div class="list-group">
  <% @categories.each do |category| %>
    <%= link_to category.name, category_path(category.id),class:'list-group-item' %>
  <%end%>
</div>
<%end %>

app/views/publishers/create.html.erb
<h1>Publishers#create</h1>
<p>Find me in app/views/publishers/create.html.erb</p>

app/views/publishers/destroy.html.erb
<h1>Publishers#destroy</h1>
<p>Find me in app/views/publishers/destroy.html.erb</p>

app/views/publishers/edit.html.erb
<h1>Publishers#edit</h1>
<p>Find me in app/views/publishers/edit.html.erb</p>

app/views/publishers/index.html.erb
<h1>Publishers#index</h1>
<p>Find me in app/views/publishers/index.html.erb</p>

app/views/publishers/new.html.erb
<h2>Add New publisher</h2>

<%= form_for @publisher do |f| %>
  <!-- check for errors -->
  <% if @publisher.errors.any? %>
    <% @publisher.errors.full_messages.each do |msg| %>
      <!-- show errors -->
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <%end%>
  <%end%>
  <div class="form-group">
    <%= f.label :name %><br/>
    <%= f.text_field :name, class:'from-control' %><br/>
  </div>

  <%= f.submit "Submit", class:'btn btn-primary' %>
  <%= link_to "Cancel", publishers_path, class:'btn btn-default' %>
<%end%>

app/views/publishers/show.html.erb
<h1>Publishers#show</h1>
<p>Find me in app/views/publishers/show.html.erb</p>

app/views/publishers/update.html.erb
<h1>Publishers#update</h1>
<p>Find me in app/views/publishers/update.html.erb</p>